# Generated by Django 5.1.3 on 2024-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_feedback_mobile_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
